# Generated by Django 5.2.5 on 2025-09-28 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='notes.note'),
        ),
        migrations.AddField(
            model_name='vocatopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voca_topics', to='notes.topic'),
        ),
        migrations.AddField(
            model_name='vocatopic',
            name='voca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voca_topics', to='notes.voca'),
        ),
        migrations.AddField(
            model_name='vocadetail',
            name='voca_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='notes.vocatopic'),
        ),
        migrations.AlterUniqueTogether(
            name='vocatopic',
            unique_together={('topic', 'voca')},
        ),
    ]
