# Generated by Django 5.2.5 on 2025-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('note', 'title'), name='unique_topic_title_per_note'),
        ),
    ]
